---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-release
  - name: local-volume-release
  - name: cf-release

outputs:
  - name: generated-manifest-localvolume

params:
  DEPLOYMENTS_DIR: replace-me
  ENVIRONMENT_NAME: replace-me
  BOSH_PASSWORD: replace-me
  BOSH_TARGET: replace-me
  BOSH_USERNAME: replace-me

run:
  path: local-volume-release/scripts/ci/generate_deployment_manifests
